### PR TITLE
Fixed Styling and Added criteria for new subjects [Issue #22]

### PR DESCRIPTION
**Pull request by Pranav-JJ**
As mentioned in Issue #22, I have fixed certain styling and spelling errors in the website, and added subject criteria.

1. Overflowing footer is fixed:
image

2. Spelling errors fixed:
image

image

3. Added criteria of Subject Teacher for each new added subject:
image

image

### CODE REVIEW

**Comment by hollermay** [comment]
Please resolve the conflicts and ping me

**Comment by Pranav-JJ** [comment]
@hollermay I think it was because a PR which was issued after me was merged with the same issue addressed. I have resolved the conflict, please review.

**Comment by hollermay** [comment]
Okay it's completed now

**Comment by hollermay** [comment]
Okay it's completed now

**Pull request merged**
