### PR TITLE
added validations to AddSubject component

### PR DESCRIPTION
**Pull request by abhijithhegde**
#2 

1.marked all the fields as required to prevent empty form submission
2.modified the input field to text and added input handler to only allow positive numbers

### CODE REVIEW

**Comment by abhijithhegde** [comment]
@hollermay it's fixed!

**Comment by abhijithhegde** [comment]
hey can you add the hacktoberfest label please?

**Comment by SuyashRajput** [comment]
@hollermay I can still add empty subjects
image

**Comment by abhijithhegde** [comment]
How, the form wont submit without filling all the 3 fields?

**Comment by hollermay** [comment]
> @hollermay I can still add empty subjects image

Do it then

**Comment by abhijithhegde** [comment]
@hollermay can you check once?
image

**Comment by hollermay** [comment]
> How, the form wont submit without filling all the 3 fields?
I'm checking it

**Comment by hollermay** [comment]
> @hollermay can you check once? image

It's in the function managedata in AddSubject.js file

**Comment by abhijithhegde** [comment]
> It's in the function managedata in AddSubject.js file
You're able to submit without filling the form?
No because it's in the function that prevents you to submit an empty field

**Comment by abhijithhegde** [comment]
@hollermay so it's already fixed right?

**Comment by hollermay** [comment]
@abhijithhegde  yes it's already been taken care of :)

**Pull request merged**
